# Labels for GitHub issues and PRs
# https://docs.github.com/en/rest/issues/labels

# Type labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: enhancement"
  color: "a2eeef"
  description: "Improvement to existing feature"

- name: "type: documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "type: question"
  color: "d876e3"
  description: "Further information is requested"

- name: "type: refactor"
  color: "fbca04"
  description: "Code refactoring"

# Priority labels
- name: "priority: critical"
  color: "b60205"
  description: "Critical priority - must be fixed ASAP"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# Status labels
- name: "status: blocked"
  color: "d93f0b"
  description: "Blocked by other issues or external factors"

- name: "status: in progress"
  color: "fbca04"
  description: "Currently being worked on"

- name: "status: needs review"
  color: "0e8a16"
  description: "Needs code review"

- name: "status: ready"
  color: "0e8a16"
  description: "Ready to be worked on"

# Component labels
- name: "component: api"
  color: "5319e7"
  description: "Related to API/webhook handler"

- name: "component: ai"
  color: "5319e7"
  description: "Related to AI generation"

- name: "component: bitrix24"
  color: "5319e7"
  description: "Related to Bitrix24 integration"

- name: "component: deployment"
  color: "5319e7"
  description: "Related to deployment and infrastructure"

- name: "component: ci/cd"
  color: "5319e7"
  description: "Related to CI/CD workflows"

# Other labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "automated"
  color: "ededed"
  description: "Automated by bots"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "security"
  color: "d73a4a"
  description: "Security related issue"
