/**
 * /idea command handler
 */

import { aiService } from "../services/ai.service.js";
import { CommandHandler } from "../types/index.js";
import { handleError } from "../utils/errors.js";
import { createLogger } from "../utils/logger.js";

const logger = createLogger("Handler:Idea");

export const ideaHandler: CommandHandler = async (ctx) => {
  const args =
    ctx.message && "text" in ctx.message
      ? ctx.message.text.split(" ").slice(1)
      : [];

  const topic = args[0]?.toLowerCase();

  logger.info(`Idea command received with topic: ${topic || "random"}`);

  try {
    // Show typing indicator
    await ctx.sendChatAction("typing");

    // Generate idea
    const idea = await aiService.generateIdea({ topic });

    // Send idea
    await ctx.reply(`💡 ${idea.text}`);

    // Log result
    logger.debug(`Idea generated by: ${idea.generatedBy}`);
  } catch (error) {
    await handleError(ctx, error as Error, "IdeaHandler");
  }
};
