/**
 * /idea command handler
 */

import { aiService } from "../services/ai.service.js";
import { CommandHandler } from "../types/index.js";
import { handleError } from "../utils/errors.js";
import { createLogger } from "../utils/logger.js";

const logger = createLogger("Handler:Idea");

export const ideaHandler: CommandHandler = async (ctx) => {
  const args =
    ctx.message && "text" in ctx.message
      ? ctx.message.text.split(" ").slice(1)
      : [];

  const topic = args[0]?.toLowerCase();

  logger.info(`Idea command received with topic: ${topic || "random"}`);

  try {
    // Generate idea (removed typing indicator - may cause blocking)
    logger.info("Calling aiService.generateIdea...");
    const idea = await aiService.generateIdea({ topic });
    logger.info(
      `Idea received from ${idea.generatedBy}: ${idea.text.substring(0, 50)}...`
    );

    // Send idea with formatting
    logger.info("Sending reply to user...");
    const formattedMessage = `💡 <b>AI-FIRST БИЗНЕС-ИДЕЯ</b>\n\n${idea.text}`;
    await ctx.reply(formattedMessage, { parse_mode: "HTML" });
    logger.info("Reply sent successfully!");

    // Log result
    logger.debug(`Idea generated by: ${idea.generatedBy}`);
  } catch (error) {
    logger.error("Error in ideaHandler", error as Error);
    await handleError(ctx, error as Error, "IdeaHandler");
  }
};
