/**
 * Daily idea generation endpoint
 * Called by GitHub Actions to send scheduled ideas
 */

import { config } from "../src/config/index.js";
import { aiService } from "../src/services/ai.service.js";

interface RequestBody {
  chat_id: string;
  topic?: string;
}

export default async (req: any, res: any) => {
  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { chat_id, topic } = req.body as RequestBody;

    if (!chat_id) {
      return res.status(400).json({ error: "chat_id is required" });
    }

    console.log(
      `[DailyIdea] Generating idea for chat ${chat_id}, topic: ${topic || "random"}`
    );

    // Generate idea
    const idea = await aiService.generateIdea({ topic });

    console.log(
      `[DailyIdea] Idea generated by ${idea.generatedBy}, sending to Telegram...`
    );

    // Send idea to Telegram
    const message = `💡 <b>AI-FIRST БИЗНЕС-ИДЕЯ</b>\n\n${idea.text}`;

    const telegramResponse = await fetch(
      `https://api.telegram.org/bot${config.token}/sendMessage`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          chat_id,
          text: message,
          parse_mode: "HTML",
        }),
      }
    );

    if (!telegramResponse.ok) {
      const error = await telegramResponse.json();
      console.error("[DailyIdea] Telegram API error:", error);
      return res
        .status(500)
        .json({ error: "Failed to send to Telegram", details: error });
    }

    console.log(`[DailyIdea] Idea sent successfully to chat ${chat_id}`);

    return res.status(200).json({
      ok: true,
      idea: idea.text,
      generatedBy: idea.generatedBy,
      sentTo: chat_id,
    });
  } catch (error: any) {
    console.error("[DailyIdea] Error:", error);
    return res.status(500).json({
      error: "Failed to generate or send idea",
      message: error.message,
    });
  }
};
